### ISSUE TITLE
Maybe offer a `provision` attribute to `app.yml` which points to a remote shell script.

### ISSUE THREAD

**Issue by howardroark** [seven1m/do-install-button#14]
I think it would be nice if the app.yml file could specify a http shell script to run as the root user.  It would keep the app.yml file nice and clean and the script could just reside in the repo in question.

Thoughts?

**Comment by seven1m** [comment]
I had intended to work on this originally but never got around to it. I'm open to PRs, but I don't think I'll be doing it myself.
