### ISSUE TITLE
shields.io compatible badge

### ISSUE THREAD

**Issue by Nowaker** [seven1m/do-install-button#5]
Your badge doesn't look good with other badges from shields.io. Just have a look: https://github.com/virtkick/virtkick-starter#virtkick-take-cloud-back Any chance to get an alternative badge? shields.io is widespread, all new badges should be aiming to be compatible with them. There are three layouts of their badges, lookup at http://shields.io/.

**Comment by seven1m** [comment]
@Nowaker please submit a Pull Request and I'll merge.

**Comment by seven1m** [comment]
@Nowaker I just figured out you can make your own button with shields.io like this: https://img.shields.io/badge/install-DigitalOcean-479de4.svg?style=flat-square

You can change your markdown to the following to use this button style instead of the default one:

```markdown
[![Install on DigitalOcean](https://img.shields.io/badge/install-DigitalOcean-479de4.svg?style=flat-square)](http://installer.71m.us/install?url=https://github.com/churchio/onebody)
```
