### ISSUE TITLE
DO install button leaves users vulnerable to CSRF

### ISSUE THREAD

**Issue by vlad902** [seven1m/do-install-button#7]
The installer does not have a CSRF token, meaning that if a user has authorized the DO install button, clicking anywhere on a third-party website could allow that third party website to launch a VM on behalf of the user.

The attack is:
1) User visits a malicious website evil.com
2) evil.com launches an invisible submit button over the entire page, with a form pointing to your installer's '/install' endpoint and valid values for size/region/agree/url with the url pointing to a repository of their choosing.
3) If/when a user clicks anywhere on the page, it will launch a VM on behalf of evil.com. This might also be achievable by javascript

This attack is mitigated by the fact that DO will email the user their root password, but this is still confusing and dangerous. You should include a CSRF token in the form and check it.

**Comment by seven1m** [comment]
@vlad902 thanks for pointing this out! For some reason I just now found this issue on GitHub -- my notification settings failed me. I didn't mean to ignore you!

I have submitted PR #8 that should fix this. Care to review?

**Comment by vlad902** [comment]
That fix looks correct to me.
